!
! THIS SUBROUTINE CALCULATES THE PACKED BED OF SPHERES HEAT TRANSFER
! COEFFICIENT
!
SUBROUTINE HCOOL(PLAVG, TLAVG, MDOTL, EPS, R, MU, K,CP,HCL)
IMPLICIT NONE
!
! VARIABLES USED IN HCOOL
!
! PLAVG = AVERAGE COOLANT PRESSURE THROUGH POROUS WALL
! TLAVG = AVERAGE COOLANT TEMPERATURE THROUGH POROUS WALL
! MDOTL = COOLANT MASS FLOW RATE THROUGH POROUS WALL
! PR = COOLANT PRANDTL NUMBER
! MU = COOLANT VISCOSITY
! K = COOLANT THERMAL CONDUCTIVITY
! RHO = COOLANT DENSITY
! CP = COOLANT SPECIFIC HEAT
! EPS=POROSITY
! R = POROUS SPHERE RADIUS
! HCL = PACKED BED OF SPHERES HEAT TRANSFER COEFFICIENT
! RHOB = COOLANT DENSITY AT BULK CONDITIONS
! REDP = COOLANT REYNOLD'S NUMBER
!
! DECLARE VARIABLES
!
DOUBLE PRECISION PLAVG, TLAVG, MDOTL, PR,MU,CP,K
DOUBLE PRECISION EPS, R, HCL, REDP
CHARACTER*64 COOLANT_MATERIAL

COMMON /MATERIALBLK/COOLANT_MATERIAL
!

! CALCULATE PRANDTL NUMBER AND REYNOLD'S NUMBER
!
PR = (MU*CP)/K
REDP = (2.0*R*MDOTL)/(MU*EPS*(1.0-EPS))
!
! CALCULATE THE PACKED BED OF SPHERES HEAT TRANSFER COEFFICIENT
!
HCL = (K/(2.0*R))*((1.0-EPS)/EPS)*(0.5*(REDP**0.5) &
+ (0.2*(REDP**(2.0/3.0))))*(PR**(1.0/3.0))
RETURN
!
! END HCOOL SUBROUTINE
!
END