! THIS SUBROUTINE CALCULATES THE HOT GAS SIDE HEAT TRANSFER
! COEFFICIENT INCLUDING THE EFFECT OF BLOWING RATIO
!
SUBROUTINE HOTGAS(TWH, THROATD, MDOT, W, GAM, T0G, TG, &
MDOTL, PI, EPS, TAW, MU0F, CP0F, PR0F, HG)
IMPLICIT NONE
!
! VARIABLES USED IN HOTGAS
!
! TWH = HOT GAS SIDE SOLID SURFACE TEMPERATURE
! THROATD = NOZZLE AERODYNAMIC THROAT DIAMETER
! MDOT = COMBUSTION GAS MASS FLOW RATE
! W = VISCOSITY, TEMPERATURE EXPONENT
! GAM = RATIO OF SPECIFIC HEATS FOR COMBUSTION GASES
! TOG = COMBUSTION GAS STAGNATION TEMPERATURE
! TG = COMBUSTION GAS STATIC TEMPERATURE AT THROAT
! MDOTL = COOLANT MASS FLOW RATE THROUGH POROUS WALL
! PI= 3.14159
! EPS = POROSITY
! TAW = ADIABATIC WALL TEMPERATURE
! HG = HOT GAS SIDE HEAT TRANSFER COEFFICIENT
! AT = NOZZLE AERODYNAMIC THROAT AREA
! MUOF = COMBUSTION GAS VISCOSITY AT STAGNATION TEMPERATURE
! CPOF = COMBUSTION GAS SPECIFIC HEAT AT STAGNATION TEMPERATURE
! BR = BLOWING RATIO
! SIGMA = BARTZ' EQUATION CONSTANT
! HGO = HOT GAS SIDE HEAT TRANSFER COEFFICIENT WITHOUT BLOWING
! PROF = COMBUSTION GAS PRANDTL NUMBER AT STAGNATION TEMPERATURE
! RHOFUF = MASS FLUX OF COMBUSTION GASES
!
! DECLARE VARIABLES
!
DOUBLE PRECISION TWH, THROATD, MDOT, W, GAM, T0G, TG
DOUBLE PRECISION MDOTL ,PI, EPS, TAW, HG, AT, MU0F, CP0F
DOUBLE PRECISION RHOL_MAX, MUL_MAX, PLAVG, KL_MAX,  CPL_MAX 
DOUBLE PRECISION BR, SIGMA, HG0, PR0F, RHOFUF,MASS_FLOW_GAS,G

CHARACTER*64 FILE2,FLUX_METHOD,COOLANT_MATERIAL
DOUBLE PRECISION T_REF,MUF_REF, CPF_REF, KF_REF,PRF_REF,MDOTF,RE_REF,St_REF
DOUBLE PRECISION L_CH,R_CONST,U,P_STATIC

!
! THIS COMMON BLOCK CONTAINS OUTPUT VARIABLES FROM HOTGAS
!
COMMON /HGBLK/MASS_FLOW_GAS
COMMON /RATIOBLK/BR
COMMON /ERROR_BR_FILEBLK/FILE2
COMMON /METHODBLK/FLUX_METHOD
COMMON /FLOWBLK/L_CH,U
COMMON /MATERIALBLK/COOLANT_MATERIAL


!
! CALCULATE THE ADIABATIC WALL TEMPERATURE
!
CALL FINDTAW(TG, T0G, TWH, TAW)
!


IF     (FLUX_METHOD=='rocket') THEN
! CALCULATE THE AERODYNAMIC THROAT AREA
!
AT = (PI*(THROATD**2.0))/4.0   
! CALCULATE THE MASS FLUX OF THE COMBUSTION GASES
!
RHOFUF = MDOT/AT
!
! CALCULATE THE BLOWING RATIO
!
!BR = MDOTL/(RHOFUF*EPS)
BR = MDOTL/(RHOFUF)
!
! THIS LIMITER PREVENTS THE BLOWING RATIO TO EXCEED 0.01
!
!   IF (BR.GE.1.17D-02) THEN
!   OPEN(UNIT= 13,FILE=FILE2)
!   WRITE (13, *) 'MDOTL ',MDOTL
!   WRITE (13,*) 'BR ',BR
!   WRITE (13,*) 'THE BLOWING RATIO HAS EXCEEDED 1.17 PERCENT'
!   CLOSE(13)
!   STOP   
!   END IF
!    
    
    
!when applied to rocket throat region use the Barz method
! CALCULATE SIGMA
!
SIGMA = 1.0/(((0.5*(TWH/T0G)*((GAM+1.0)/2.0)+0.5)**(0.8-0.2*W)) &
*(((GAM+1.0)/2.0)**(0.2*W)))
!
! CALCULATE THE HEAT TRANSFER COEFFICIENT WITHOUT BLOWING EFFECTS
!
HG0 = ((0.026/(THROATD**0.2))*(((MU0F**0.2)*CP0F)/(PR0F**0.6)) &
*((RHOFUF)**0.8)*((2.0)**0.1))*SIGMA
!
!
!
!
ELSEIF (FLUX_METHOD=='plate')  THEN 
BR= MDOTL/MASS_FLOW_GAS   
!when applied to plate region use the  Eckert's reference Enthalpy method
T_REF=0.5* (TWH+TG)+0.22* (TAW-TG)
!
CALL HOTGASPROP(T_REF, MUF_REF, CPF_REF, KF_REF)
!
!calculate Pr number under the reference temperature
PRF_REF = (MUF_REF*CPF_REF)/KF_REF
!input characteristic length 
L_CH=1.5
!calulate Re number under the reference temperature 
RE_REF=MASS_FLOW_GAS*L_CH/(T_REF*MUF_REF)
St_REF=0.0287/((RE_REF**0.2)*(PRF_REF**0.4))
HG0=MASS_FLOW_GAS*St_REF*CPF_REF
END IF







! GENERATE  PROPERTIES AT THE AVERAGE PRESSURE AND THE HIGHEST  TEMPERATURE
IF       (COOLANT_MATERIAL=='H2')  THEN
CALL H2PROP(PLAVG, TWH, MUL_MAX, KL_MAX, RHOL_MAX, CPL_MAX)
ELSE IF  (COOLANT_MATERIAL=='H2O') THEN
    
ELSE IF  (COOLANT_MATERIAL=='CO2') THEN
    
ELSEIF       (COOLANT_MATERIAL=='N2')  THEN
CALL N2PROP(PLAVG, TWH, MUL_MAX, KL_MAX, RHOL_MAX, CPL_MAX)  
    
ELSE IF  (COOLANT_MATERIAL=='Air') THEN
CALL AIRPROP(PLAVG, TWH, MUL_MAX, KL_MAX, RHOL_MAX, CPL_MAX)
ELSE IF  (COOLANT_MATERIAL=='Ar')  THEN
    
ELSE IF  (COOLANT_MATERIAL=='He')  THEN
    
END IF

G=CPL_MAX*MDOTL/HG0
G=G*( (CPL_MAX/CPF_REF)**0.6 )

HG=HG0
! INCLUDE BLOWING EFFECTS
!
!HG = HG0*(1.0-38.0*BR)
IF (G.GT.0) THEN
HG=HG0*G/( (1+G/3.0)*(1+G/3.0)*(1+G/3.0)-1.0 )
HG=HG0*G/(exp(G)-1)
ENDIF       


RETURN
!
! END HOTGAS SUBROUTINE
!
END
!
