! THIS SUBROUTINE CALCULATES THE COOLANT TEMPERATURE PROFILE
!
SUBROUTINE TLIQUID(TSOLD, TLOLD, HCL, TLNEW)
IMPLICIT NONE
!
! VARIABLES USED IN TLIQUID
!
! TLOLD = COOLANT TEMPERATURE PROFILE AT PREVIOUS TIME STEP
! MDOTL = COOLANT MASS FLOW RATE THROUGH POROUS SOLID
! EPS = POROSITY
! R = POROUS SPHERE RADIUS
! TI3 = COOLANT BULK TEMPERATURE
! DX = INCREMENTAL DISTANCE STEP SIZE
! CO = PROPORTIONALITY CONSTANT FOR SOLID SURFACE AREA
! TSOLD = SOLID TEMPERAW PROFILE AT PREVIOUS TIME STEP
! KL = COOLANT THERMAL CONDUCTIVITIES
! RHOL = COOLANT DENSITIES
! MULAVG = AVERAGE COOLANT VISCOSITY
! RHOLAVG = AVERAGE COOLANT DENSITY
! TLNEW = COOLANT TEMPERATURE PROFILE AT NEW TIME STEP
! KW = SOLID THERMAL CONDUCTIVITY
! DELTAP = PRESSURE DIFFERENCE ACROSS POROUS WALL
! PERMEABLE = PERMEABILITY
! PL = LOCAL COOLANT PRESSURE
! KLL = LOCAL COOLANT THERMAL CONDUCTIVITY
! CPL = COOLANT SPECIFIC HEATS
! UL = COOLANT VELOCITIES
! HCL = PACKED BED OF SPHERES HEAT TRANSFER COEFFICIENT
! PB = COOLANT CHANNEL PRESSURE
! DP = INCREMENTAL PRESSURE DLFFERENCE
! C1, C2, C3 = PLACE HOLDER CONSTANTS
! PLAVG = AVERAGE COOLANT PRESSURE WITHIN POROUS WALL
! TLAVG = AVERAGE COOLANT TEMPERATURE WITHIN POROUS WALL
! RHOB = COOLANT DENSITY AT BULK CONDITIONS
! THICKNESS = POROUS WALL THICKNESS
! MULL = LOCAL COOLANT VISCOSITY
! CPLL = LOCAL COOLANT SPECIFIC HEAT
! ULL = LOCAL COOLANT VELOCITY
! CPLAVG = AVERAGE COOLANT SPECIFIC HEAT
! KLAVG = AVERAGE COOLANT THERMAL CONDUCTIVITY
! N = INDEX USED FOR SOLID TEMPERATURE ARRAY
! M = INDEX USED FOR COOLANT TEMPERATURE ARRAY
! LASTX = GRID SIZE
!
! DECLARE VARIABLES
!
DOUBLE PRECISION TLOLD, MDOTL, EPS, R, TB, DX, C0, TSOLD, KL, RHOL
DOUBLE PRECISION PLAVG, TLNEW, KW, DELTAP, PERMEABLE
DOUBLE PRECISION PB, DP,PL,MUL,CPL,UL,HCL
DOUBLE PRECISION C1, C2, C3, TLAVG, RHOB, THICKNESS
!DOUBLE PRECISION MULL, CPLL, ULL, CPLAVG, KLAVG
INTEGER N, M, LASTX
CHARACTER*64 COOLANT_MATERIAL
!
! DIMENSION VARIABLES THAT ARE ARRAYS
!
DIMENSION TLOLD(20000), TSOLD(20000), KL(20000)
DIMENSION RHOL(20000), CPL(20000), UL(20000) ,MUL(20000)
DIMENSION TLNEW(20000),PL(20000) ,HCL(20000)
!
! THIS COMMON BLOCK CONTAINS THE GRID DIMENSIONS
!
COMMON /DIMEN/LASTX, DX
!
! THIS COMMON BLOCK CONTAINS VARIABLES COMMON TO TSOLID AND TLIQUID
!
COMMON /TSTL/C0, EPS, R, PB, TB, KW,  MDOTL
!
! THIS COMMON BLOCK CONTAINS VARIABLES COMMON TO TLIQUID ONLY
!
COMMON /TLBLK/PLAVG, TLAVG, RHOB,DP,DELTAP,PERMEABLE,THICKNESS
!
COMMON /MATERIALBLK/COOLANT_MATERIAL


!
! CALCULATE THE PACKED BED OF SPHERES HEAT TRANSFER COEFFICIENT
!
!
! BEGIN MAIN LOOP TO STEP THROUGH THE POROUS WALL
!
DO N= 1,(LASTX+1)
M=N+2
!
! CALCULATE THE COOLANT PRESSURE THROUGH EACH DX POROUS WALL
PL(LASTX+1)=PLAVG
! GENERATE  PROPERTIES AT THE LOCAL TEMPERATURE
!
IF       (COOLANT_MATERIAL=='H2')  THEN
CALL H2PROP(PL((LASTX+1)-N+1), TLOLD((LASTX+3)-N+1), MUL((LASTX+1)-N+1), KL((LASTX+1)-N+1), RHOL((LASTX+1)-N+1), CPL((LASTX+1)-N+1))
ELSE IF  (COOLANT_MATERIAL=='H2O') THEN
    
ELSE IF  (COOLANT_MATERIAL=='CO2') THEN
    
ELSEIF   (COOLANT_MATERIAL=='N2')  THEN
CALL N2PROP(PL((LASTX+1)-N+1), TLOLD((LASTX+3)-N+1), MUL((LASTX+1)-N+1), KL((LASTX+1)-N+1), RHOL((LASTX+1)-N+1), CPL((LASTX+1)-N+1))   
    
ELSE IF  (COOLANT_MATERIAL=='Air') THEN
CALL AIRPROP(PL((LASTX+1)-N+1), TLOLD((LASTX+3)-N+1), MUL((LASTX+1)-N+1), KL((LASTX+1)-N+1), RHOL((LASTX+1)-N+1), CPL((LASTX+1)-N+1))   
ELSE IF  (COOLANT_MATERIAL=='Ar')  THEN
    
ELSE IF  (COOLANT_MATERIAL=='He')  THEN
    
END IF


DP=MDOTL*(DX*MUL((LASTX+1)-N+1))/(PERMEABLE*RHOL((LASTX+1)-N+1))
IF ( N<(LASTX+1) ) THEN 
PL((LASTX+1)-N) = PL((LASTX+1)-N+1)+DP
ENDIF


!
! CALCULATE THE LOCAL COOLANT VELOCITY
!
UL((LASTX+1)-N+1) = MDOTL/(EPS*RHOL((LASTX+1)-N+1))

!
! SET THE FIRST TWO TEMPERATURES BEFORE THE POROUS WALL EQUAL
! TO THE BULK TEMPERATURE
!
TLNEW(1) = TB
TLNEW(2) = TB
!

CALL HCOOL(PL((LASTX+1)-N+1), TLOLD((LASTX+3)-N+1), MDOTL, EPS, R, MUL((LASTX+1)-N+1),KL((LASTX+1)-N+1),CPL((LASTX+1)-N+1),HCL((LASTX+1)-N+1))
! DEFINE THE PLACEHOLDER CONSTANTS C1 AND C2
!
END DO

PB=PL(1)

DO N= 1,(LASTX+1)
M=N+2
C1 = KL(N)/(DX**2.0)
C2 = (RHOL(N)*UL(N)*CPL(N))/DX
!
! DEFINE THE PLACEHOLDER CONSTANT C3 BASED UPON FIRST OR LAST GRID
! POINTS
!
IF ((N.NE.1).AND.(N.NE.(LASTX+1))) THEN
C3 = (HCL(N)*C0)/(EPS*R)
ELSE
C3 = (HCL(N)*C0)/(2.0*EPS*R)
END IF
!
! CALCULATE THE NEW COOLANT TEMPERATURE AT THIS LOCATION
!
TLNEW(M) = (1.0/(C2+C3-C1))*(C1*( TLNEW(M-2)-2.0*TLNEW(M-1) )+C2*TLNEW(M-1)+C3*TSOLD(N))
!
! END THE MAIN LOOP
!
END DO
!
RETURN
!
! END TLIQUID SUBROUTINE
!
END
